---
title: "Homework 6"
author: "Savannah Jeffrey"
date: "2023-07-06"
output: html_document
---

## Question 1

Load packages 

```{r}
library(palmerpenguins)
library(dplyr)
library(ggplot2)
```

#### 1A

Remove NA from sex list 
```{r}
peng <- dplyr:: filter(.data = penguins, sex != "NA")
```

Make plot 
```{r}
peng.plot <- ggplot(data = peng, mapping = aes(x = sex, y = flipper_length_mm, fill = sex)) +
  geom_violin() +
  scale_fill_manual(values = c("female" = "#00b4d8",
                               "male" = "#57cc99"))
```

#### 1B 

```{r}
peng.plot +
  labs(x = "Sex", y = "Flipper Length (mm)") +
  theme (panel.background = element_blank(), axis.line = element_line(color = "black"), legend.title = element_blank(), legend.position = c(0.8,0.2)) +
  facet_grid(. ~ species)
```

## Question 2

#### 2A

```{r}
peng.plot2 <- ggplot(data = peng, mapping = aes(x = flipper_length_mm, y = island, fill = island)) +
  geom_violin() +
  scale_fill_manual(values = c("Dream" = "#F15BB5",
                                "Torgersen" = "#FEE440",
                                "Biscoe" = "#9B5DE5")) 
  
```

```{r}
peng.plot2 +
  labs(x = "Flipper Length (mm)", y = "Island")  +
  theme (panel.background = element_blank(), axis.line = element_line(color = "black"), legend.title = element_blank(), legend.position = c(0.9,0.7))
```

#### 2B

I used Coolers from the beginning to make the graphs so I wasn't sure how to do this question.. 

## Question 3

Load cowplot package
```{r eval=FALSE}
library(cowplot)
```

```{r}
cowplot :: plot_grid(peng.plot, peng.plot2, ncol = 2, nrow = 1)
```
